export type Country = { code: string; label: string };

export const countries: Country[] = [
	{ code: 'ES', label: 'España' },
	{ code: 'PT', label: 'Portugal' },
	{ code: 'FR', label: 'Francia' },
	{ code: 'DE', label: 'Alemania' },
	{ code: 'IT', label: 'Italia' },
	{ code: 'GB', label: 'Reino Unido' },
	{ code: 'US', label: 'Estados Unidos' },
	{ code: 'AD', label: 'Andorra' },
	{ code: 'AE', label: 'Emiratos Árabes Unidos' },
	{ code: 'AF', label: 'Afganistán' },
	{ code: 'AG', label: 'Antigua y Barbuda' },
	{ code: 'AL', label: 'Albania' },
	{ code: 'AM', label: 'Armenia' },
	{ code: 'AO', label: 'Angola' },
	{ code: 'AR', label: 'Argentina' },
	{ code: 'AT', label: 'Austria' },
	{ code: 'AU', label: 'Australia' },
	{ code: 'AZ', label: 'Azerbaiyán' },
	{ code: 'BA', label: 'Bosnia y Herzegovina' },
	{ code: 'BB', label: 'Barbados' },
	{ code: 'BD', label: 'Bangladés' },
	{ code: 'BE', label: 'Bélgica' },
	{ code: 'BF', label: 'Burkina Faso' },
	{ code: 'BG', label: 'Bulgaria' },
	{ code: 'BH', label: 'Bahréin' },
	{ code: 'BI', label: 'Burundi' },
	{ code: 'BJ', label: 'Benín' },
	{ code: 'BN', label: 'Brunéi' },
	{ code: 'BO', label: 'Bolivia' },
	{ code: 'BR', label: 'Brasil' },
	{ code: 'BS', label: 'Bahamas' },
	{ code: 'BT', label: 'Bután' },
	{ code: 'BW', label: 'Botsuana' },
	{ code: 'BY', label: 'Bielorrusia' },
	{ code: 'BZ', label: 'Belice' },
	{ code: 'CA', label: 'Canadá' },
	{ code: 'CD', label: 'República Democrática del Congo' },
	{ code: 'CF', label: 'República Centroafricana' },
	{ code: 'CG', label: 'República del Congo' },
	{ code: 'CH', label: 'Suiza' },
	{ code: 'CI', label: 'Costa de Marfil' },
	{ code: 'CL', label: 'Chile' },
	{ code: 'CM', label: 'Camerún' },
	{ code: 'CN', label: 'China' },
	{ code: 'CO', label: 'Colombia' },
	{ code: 'CR', label: 'Costa Rica' },
	{ code: 'CU', label: 'Cuba' },
	{ code: 'CV', label: 'Cabo Verde' },
	{ code: 'CY', label: 'Chipre' },
	{ code: 'CZ', label: 'Chequia' },
	{ code: 'DJ', label: 'Yibuti' },
	{ code: 'DK', label: 'Dinamarca' },
	{ code: 'DM', label: 'Dominica' },
	{ code: 'DO', label: 'República Dominicana' },
	{ code: 'DZ', label: 'Argelia' },
	{ code: 'EC', label: 'Ecuador' },
	{ code: 'EE', label: 'Estonia' },
	{ code: 'EG', label: 'Egipto' },
	{ code: 'ER', label: 'Eritrea' },
	{ code: 'ET', label: 'Etiopía' },
	{ code: 'FI', label: 'Finlandia' },
	{ code: 'FJ', label: 'Fiyi' },
	{ code: 'FM', label: 'Micronesia' },
	{ code: 'GA', label: 'Gabón' },
	{ code: 'GD', label: 'Granada' },
	{ code: 'GE', label: 'Georgia' },
	{ code: 'GH', label: 'Ghana' },
	{ code: 'GM', label: 'Gambia' },
	{ code: 'GN', label: 'Guinea' },
	{ code: 'GQ', label: 'Guinea Ecuatorial' },
	{ code: 'GR', label: 'Grecia' },
	{ code: 'GT', label: 'Guatemala' },
	{ code: 'GW', label: 'Guinea-Bisáu' },
	{ code: 'GY', label: 'Guyana' },
	{ code: 'HN', label: 'Honduras' },
	{ code: 'HR', label: 'Croacia' },
	{ code: 'HT', label: 'Haití' },
	{ code: 'HU', label: 'Hungría' },
	{ code: 'ID', label: 'Indonesia' },
	{ code: 'IE', label: 'Irlanda' },
	{ code: 'IL', label: 'Israel' },
	{ code: 'IN', label: 'India' },
	{ code: 'IQ', label: 'Irak' },
	{ code: 'IR', label: 'Irán' },
	{ code: 'IS', label: 'Islandia' },
	{ code: 'JM', label: 'Jamaica' },
	{ code: 'JO', label: 'Jordania' },
	{ code: 'JP', label: 'Japón' },
	{ code: 'KE', label: 'Kenia' },
	{ code: 'KG', label: 'Kirguistán' },
	{ code: 'KH', label: 'Camboya' },
	{ code: 'KI', label: 'Kiribati' },
	{ code: 'KM', label: 'Comoras' },
	{ code: 'KN', label: 'San Cristóbal y Nieves' },
	{ code: 'KP', label: 'Corea del Norte' },
	{ code: 'KR', label: 'Corea del Sur' },
	{ code: 'KW', label: 'Kuwait' },
	{ code: 'KZ', label: 'Kazajistán' },
	{ code: 'LA', label: 'Laos' },
	{ code: 'LB', label: 'Líbano' },
	{ code: 'LC', label: 'Santa Lucía' },
	{ code: 'LI', label: 'Liechtenstein' },
	{ code: 'LK', label: 'Sri Lanka' },
	{ code: 'LR', label: 'Liberia' },
	{ code: 'LS', label: 'Lesoto' },
	{ code: 'LT', label: 'Lituania' },
	{ code: 'LU', label: 'Luxemburgo' },
	{ code: 'LV', label: 'Letonia' },
	{ code: 'LY', label: 'Libia' },
	{ code: 'MA', label: 'Marruecos' },
	{ code: 'MC', label: 'Mónaco' },
	{ code: 'MD', label: 'Moldavia' },
	{ code: 'ME', label: 'Montenegro' },
	{ code: 'MG', label: 'Madagascar' },
	{ code: 'MH', label: 'Islas Marshall' },
	{ code: 'MK', label: 'Macedonia del Norte' },
	{ code: 'ML', label: 'Malí' },
	{ code: 'MM', label: 'Myanmar' },
	{ code: 'MN', label: 'Mongolia' },
	{ code: 'MR', label: 'Mauritania' },
	{ code: 'MT', label: 'Malta' },
	{ code: 'MU', label: 'Mauricio' },
	{ code: 'MV', label: 'Maldivas' },
	{ code: 'MW', label: 'Malaui' },
	{ code: 'MX', label: 'México' },
	{ code: 'MY', label: 'Malasia' },
	{ code: 'MZ', label: 'Mozambique' },
	{ code: 'NA', label: 'Namibia' },
	{ code: 'NE', label: 'Níger' },
	{ code: 'NG', label: 'Nigeria' },
	{ code: 'NI', label: 'Nicaragua' },
	{ code: 'NL', label: 'Países Bajos' },
	{ code: 'NO', label: 'Noruega' },
	{ code: 'NP', label: 'Nepal' },
	{ code: 'NR', label: 'Nauru' },
	{ code: 'NZ', label: 'Nueva Zelanda' },
	{ code: 'OM', label: 'Omán' },
	{ code: 'PA', label: 'Panamá' },
	{ code: 'PE', label: 'Perú' },
	{ code: 'PG', label: 'Papúa Nueva Guinea' },
	{ code: 'PH', label: 'Filipinas' },
	{ code: 'PK', label: 'Pakistán' },
	{ code: 'PL', label: 'Polonia' },
	{ code: 'PW', label: 'Palaos' },
	{ code: 'PY', label: 'Paraguay' },
	{ code: 'QA', label: 'Catar' },
	{ code: 'RO', label: 'Rumanía' },
	{ code: 'RS', label: 'Serbia' },
	{ code: 'RU', label: 'Rusia' },
	{ code: 'RW', label: 'Ruanda' },
	{ code: 'SA', label: 'Arabia Saudita' },
	{ code: 'SB', label: 'Islas Salomón' },
	{ code: 'SC', label: 'Seychelles' },
	{ code: 'SD', label: 'Sudán' },
	{ code: 'SE', label: 'Suecia' },
	{ code: 'SG', label: 'Singapur' },
	{ code: 'SI', label: 'Eslovenia' },
	{ code: 'SK', label: 'Eslovaquia' },
	{ code: 'SL', label: 'Sierra Leona' },
	{ code: 'SM', label: 'San Marino' },
	{ code: 'SN', label: 'Senegal' },
	{ code: 'SO', label: 'Somalia' },
	{ code: 'SR', label: 'Surinam' },
	{ code: 'SS', label: 'Sudán del Sur' },
	{ code: 'ST', label: 'Santo Tomé y Príncipe' },
	{ code: 'SV', label: 'El Salvador' },
	{ code: 'SY', label: 'Siria' },
	{ code: 'SZ', label: 'Esuatini' },
	{ code: 'TD', label: 'Chad' },
	{ code: 'TG', label: 'Togo' },
	{ code: 'TH', label: 'Tailandia' },
	{ code: 'TJ', label: 'Tayikistán' },
	{ code: 'TL', label: 'Timor-Leste' },
	{ code: 'TM', label: 'Turkmenistán' },
	{ code: 'TN', label: 'Túnez' },
	{ code: 'TO', label: 'Tonga' },
	{ code: 'TR', label: 'Turquía' },
	{ code: 'TT', label: 'Trinidad y Tobago' },
	{ code: 'TV', label: 'Tuvalu' },
	{ code: 'TZ', label: 'Tanzania' },
	{ code: 'UA', label: 'Ucrania' },
	{ code: 'UG', label: 'Uganda' },
	{ code: 'UY', label: 'Uruguay' },
	{ code: 'UZ', label: 'Uzbekistán' },
	{ code: 'VA', label: 'Ciudad del Vaticano' },
	{ code: 'VC', label: 'San Vicente y las Granadinas' },
	{ code: 'VE', label: 'Venezuela' },
	{ code: 'VN', label: 'Vietnam' },
	{ code: 'VU', label: 'Vanuatu' },
	{ code: 'WS', label: 'Samoa' },
	{ code: 'YE', label: 'Yemen' },
	{ code: 'ZA', label: 'Sudáfrica' },
	{ code: 'ZM', label: 'Zambia' },
	{ code: 'ZW', label: 'Zimbabue' }
];
