<script lang="ts">
	import type { BookingQuestion } from '$lib/types';
	import { SvelteMap } from 'svelte/reactivity';
	import BookingQuestionField from './BookingQuestionField.svelte';

	const fakeQuestions: BookingQuestion[] = [
		{
			id: 'dbg-text',
			activityId: 'dbg',
			dataType: 'INPUT_TEXT',
			label: 'Nombre completo',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Introduce tu nombre como aparece en el pasaporte',
			placeholder: 'Ej: María García López',
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-textarea',
			activityId: 'dbg',
			dataType: 'TEXT_AREA',
			label: 'Observaciones',
			required: 'NOT_REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Cualquier información adicional para el guía',
			placeholder: 'Escribe aquí tus observaciones...',
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-number',
			activityId: 'dbg',
			dataType: 'INPUT_NUMBER',
			label: 'Número de participantes',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Máximo 10',
			placeholder: null,
			defaultValue: null,
			minValue: 1,
			maxValue: 10,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-age',
			activityId: 'dbg',
			dataType: 'AGE',
			label: 'Edad',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Debe ser mayor de 18 años',
			placeholder: null,
			defaultValue: null,
			minValue: 18,
			maxValue: 99,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-email',
			activityId: 'dbg',
			dataType: 'EMAIL',
			label: 'Email de contacto',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Recibirás la confirmación en este email',
			placeholder: 'ejemplo@correo.com',
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-phone',
			activityId: 'dbg',
			dataType: 'PHONE',
			label: 'Teléfono de contacto',
			required: 'NOT_REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Incluye prefijo internacional',
			placeholder: '+34 600 000 000',
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-date',
			activityId: 'dbg',
			dataType: 'DATE',
			label: 'Fecha de nacimiento',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Formato DD/MM/AAAA',
			placeholder: null,
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-birthday',
			activityId: 'dbg',
			dataType: 'BIRTHDAY',
			label: 'Cumpleaños',
			required: 'NOT_REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: null,
			placeholder: null,
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-passport-expired',
			activityId: 'dbg',
			dataType: 'PASSPORT_EXPIRED',
			label: 'Fecha de caducidad del pasaporte',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'El pasaporte debe ser válido en la fecha de la actividad',
			placeholder: null,
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-datetime',
			activityId: 'dbg',
			dataType: 'DATE_AND_TIME',
			label: 'Fecha y hora de llegada',
			required: 'NOT_REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: null,
			placeholder: null,
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-option',
			activityId: 'dbg',
			dataType: 'OPTION',
			label: 'Idioma preferido',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'El guía intentará acomodarse',
			placeholder: null,
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [
				{ id: 'opt-1', label: 'Español', value: 'es' },
				{ id: 'opt-2', label: 'Inglés', value: 'en' },
				{ id: 'opt-3', label: 'Francés', value: 'fr' }
			],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-radio',
			activityId: 'dbg',
			dataType: 'RADIO_BUTTON',
			label: 'Nivel de experiencia',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Selecciona solo uno',
			placeholder: null,
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [
				{ id: 'rad-1', label: 'Principiante', value: 'beginner' },
				{ id: 'rad-2', label: 'Intermedio', value: 'intermediate' },
				{ id: 'rad-3', label: 'Avanzado', value: 'advanced' }
			],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-multi',
			activityId: 'dbg',
			dataType: 'MULTI_OPTION',
			label: 'Alergias alimentarias',
			required: 'NOT_REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Selecciona todas las que apliquen',
			placeholder: null,
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [
				{ id: 'mul-1', label: 'Gluten', value: 'gluten' },
				{ id: 'mul-2', label: 'Lactosa', value: 'lactose' },
				{ id: 'mul-3', label: 'Frutos secos', value: 'nuts' }
			],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-checkbox',
			activityId: 'dbg',
			dataType: 'CHECKBOX',
			label: 'Acepto las condiciones',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Lectura obligatoria',
			placeholder: null,
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-check-terms',
			activityId: 'dbg',
			dataType: 'CHECK_TERMS',
			label: 'Acepto los términos de cancelación',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Política aplicable al 100%',
			placeholder: null,
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-boolean',
			activityId: 'dbg',
			dataType: 'BOOLEAN',
			label: 'Quiero recibir novedades',
			required: 'NOT_REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Enviaremos información sobre actividades similares',
			placeholder: null,
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-country',
			activityId: 'dbg',
			dataType: 'COUNTRY',
			label: 'País de residencia',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'País donde resides actualmente',
			placeholder: 'Ej: España',
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-gender',
			activityId: 'dbg',
			dataType: 'GENDER',
			label: 'Género',
			required: 'NOT_REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: null,
			placeholder: 'Ej: Mujer',
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-language',
			activityId: 'dbg',
			dataType: 'LANGUAGE',
			label: 'Idioma nativo',
			required: 'NOT_REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Idioma en el que prefieres comunicarte',
			placeholder: 'Ej: Español',
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		},
		{
			id: 'dbg-passport',
			activityId: 'dbg',
			dataType: 'PASSPORT',
			label: 'Número de pasaporte',
			required: 'REQUIRED',
			status: 'ACTIVE',
			target: 'PASSENGER',
			groupAge: ['ADULT'],
			helpText: 'Tal como aparece en el documento',
			placeholder: 'Ej: AAB123456',
			defaultValue: null,
			minValue: null,
			maxValue: null,
			options: [],
			activityOptions: [],
			createdAt: '',
			updatedAt: ''
		}
	];

	const values = new SvelteMap<string, string>(fakeQuestions.map((q) => [q.id, '']));
</script>

<h2 class="h2 mt-6">DEBUG: Tipos de campos</h2>
<p class="p-lg mt-2">Sandbox de estilos — eliminar antes de publicar</p>

<div class="mt-6 flex flex-col gap-4 rounded-xl border border-neutral-200 p-6">
	<p class="h3">Asistente 1 (Adulto)</p>
	<div class="flex flex-col gap-4">
		{#each fakeQuestions as q (q.id)}
			<BookingQuestionField
				{q}
				value={values.get(q.id) ?? ''}
				onchange={(v) => values.set(q.id, v)}
			/>
		{/each}
	</div>
</div>
