/**
 * @module activities/enums
 * @description Domain enums for the Activities resource.
 * These mirror the backend contract exactly and carry no UI or i18n dependencies.
 */

/** Publication lifecycle status of an activity. */
export enum ActivityStatus {
	APPROVED = 'APPROVED',
	DELETED = 'DELETED',
	DRAFT = 'DRAFT',
	PENDING_REVIEW = 'PENDING_REVIEW',
	PUBLISHED = 'PUBLISHED',
	REJECTED = 'REJECTED',
	UNPUBLISHED = 'UNPUBLISHED'
}

/** Commercial classification of an activity. */
export enum ActivityKind {
	PAID_TOUR = 'PAID_TOUR',
	FREE_TOUR = 'FREE_TOUR',
	OTHER = 'OTHER'
}

/** Type of guide that leads the activity. */
export enum ActivityGuideKind {
	AUTO = 'AUTO',
	CUSTOM_LANGUAGE = 'CUSTOM_LANGUAGE',
	DRIVER = 'DRIVER',
	GUEST = 'GUEST',
	INSTRUCTOR = 'INSTRUCTOR',
	NORMAL_GUIDE = 'NORMAL_GUIDE'
}

/** Audience segments the activity is not suitable for. */
export enum ActivityNotSuitableFor {
	CHILDREN = 'CHILDREN',
	GROUPS = 'GROUPS',
	MINIMUM_AGE_18 = 'MINIMUM_AGE_18',
	PETS = 'PETS',
	WHEELCHAIR = 'WHEELCHAIR',
	BABY_STROLLERS = 'BABY_STROLLERS'
}

/** Known restrictions that apply during the activity. */
export enum ActivityRestriction {
	ALCOHOL = 'ALCOHOL',
	ALCOHOL_OR_DRUGS = 'ALCOHOL_OR_DRUGS',
	ALCOHOLIC_DRINKS_IN_VEHICLE = 'ALCOHOLIC_DRINKS_IN_VEHICLE',
	AUDIO_RECORDING = 'AUDIO_RECORDING',
	BABY_PUSHCHAIRS = 'BABY_PUSHCHAIRS',
	BABY_STROLLERS = 'BABY_STROLLERS',
	BACHELOR_BACHELORETTE_PARTIES = 'BACHELOR_BACHELORETTE_PARTIES',
	BACKPACKS = 'BACKPACKS',
	BAGS_OR_HANDBAGS = 'BAGS_OR_HANDBAGS',
	BAREFOOT = 'BAREFOOT',
	BICYCLES = 'BICYCLES',
	BOOTS = 'BOOTS',
	BRIGHT_COLORS = 'BRIGHT_COLORS',
	CAMERAS = 'CAMERAS',
	CAPS = 'CAPS',
	CHEWING_GUM = 'CHEWING_GUM',
	CLIMBING = 'CLIMBING',
	COOLER = 'COOLER',
	CRUTCHES = 'CRUTCHES',
	DIVING = 'DIVING',
	DRINKS = 'DRINKS',
	DRINKS_IN_VEHICLE = 'DRINKS_IN_VEHICLE',
	DRONES = 'DRONES',
	ELECTRIC_WHEELCHAIRS = 'ELECTRIC_WHEELCHAIRS',
	ELECTRONIC_CIGARETTES = 'ELECTRONIC_CIGARETTES',
	ELECTRONIC_DEVICES = 'ELECTRONIC_DEVICES',
	EXPLOSIVE_MATERIALS = 'EXPLOSIVE_MATERIALS',
	FEEDING_ANIMALS = 'FEEDING_ANIMALS',
	FIREWORKS = 'FIREWORKS',
	FISHING = 'FISHING',
	FLASH_PHOTOGRAPHY = 'FLASH_PHOTOGRAPHY',
	FLASHLIGHT = 'FLASHLIGHT',
	FOOD = 'FOOD',
	FOOD_IN_VEHICLE = 'FOOD_IN_VEHICLE',
	FOOD_OR_DRINKS = 'FOOD_OR_DRINKS',
	FOOD_OR_DRINKS_IN_VEHICLE = 'FOOD_OR_DRINKS_IN_VEHICLE',
	GLASS_OBJECTS = 'GLASS_OBJECTS',
	HAND_CARTS = 'HAND_CARTS',
	HEADPHONES = 'HEADPHONES',
	HIGH_HEELS = 'HIGH_HEELS',
	HIKING_POLES = 'HIKING_POLES',
	INDOOR_PHOTOGRAPHY = 'INDOOR_PHOTOGRAPHY',
	INSECT_REPELLENT = 'INSECT_REPELLENT',
	INTOXICATION = 'INTOXICATION',
	JEANS = 'JEANS',
	JEWELRY = 'JEWELRY',
	JUMPING = 'JUMPING',
	LARGE_LUGGAGE_OR_BAGS = 'LARGE_LUGGAGE_OR_BAGS',
	LITTERING = 'LITTERING',
	LOOSE_CLOTHING = 'LOOSE_CLOTHING',
	MAKING_FIRE = 'MAKING_FIRE',
	MAKING_NOISE = 'MAKING_NOISE',
	MILITARY_STYLE_CLOTHING = 'MILITARY_STYLE_CLOTHING',
	MOBILE_PHONES = 'MOBILE_PHONES',
	MOBILITY_SCOOTER = 'MOBILITY_SCOOTER',
	NON_FOLDABLE_STROLLERS = 'NON_FOLDABLE_STROLLERS',
	NON_FOLDABLE_WHEELCHAIRS = 'NON_FOLDABLE_WHEELCHAIRS',
	NUDITY = 'NUDITY',
	OPEN_SHOES = 'OPEN_SHOES',
	OTHER = 'OTHER',
	OVERSIZED_LUGGAGE = 'OVERSIZED_LUGGAGE',
	PADLOCKS = 'PADLOCKS',
	PARTY_GROUPS = 'PARTY_GROUPS',
	PETS = 'PETS',
	PETS_EXCEPT_ASSISTANCE_DOGS = 'PETS_EXCEPT_ASSISTANCE_DOGS',
	PLASTIC_BAGS = 'PLASTIC_BAGS',
	PLASTIC_BOTTLES = 'PLASTIC_BOTTLES',
	PROFESSIONAL_CAMERAS = 'PROFESSIONAL_CAMERAS',
	RED_WINE = 'RED_WINE',
	RIDING_ANIMALS = 'RIDING_ANIMALS',
	SANDALS_OR_FLIP_FLOPS = 'SANDALS_OR_FLIP_FLOPS',
	SCOOTERS = 'SCOOTERS',
	SELFIE_STICKS = 'SELFIE_STICKS',
	SHOES = 'SHOES',
	SHORT_PANTS = 'SHORT_PANTS',
	SHORT_SKIRTS = 'SHORT_SKIRTS',
	SKATEBOARDS = 'SKATEBOARDS',
	SKATES = 'SKATES',
	SKIRTS = 'SKIRTS',
	SLEEVELESS_SHIRTS = 'SLEEVELESS_SHIRTS',
	SLIPPERS = 'SLIPPERS',
	SMOKING = 'SMOKING',
	SMOKING_INDOORS = 'SMOKING_INDOORS',
	SMOKING_IN_VEHICLE = 'SMOKING_IN_VEHICLE',
	SNORKELING = 'SNORKELING',
	SPEAKERS = 'SPEAKERS',
	SPORTS_SHOES = 'SPORTS_SHOES',
	SPORTSWEAR = 'SPORTSWEAR',
	SPRAYS_OR_AEROSOLS = 'SPRAYS_OR_AEROSOLS',
	STRONG_PERFUMES = 'STRONG_PERFUMES',
	SUNGLASSES = 'SUNGLASSES',
	SUNSCREEN = 'SUNSCREEN',
	SURFBOARDS = 'SURFBOARDS',
	SWIMMING = 'SWIMMING',
	SWIMSUIT = 'SWIMSUIT',
	TABLETS = 'TABLETS',
	TIGHT_CLOTHING = 'TIGHT_CLOTHING',
	TORN_CLOTHING = 'TORN_CLOTHING',
	TOUCHING_ANIMALS = 'TOUCHING_ANIMALS',
	TOUCHING_EXHIBITS = 'TOUCHING_EXHIBITS',
	TOUCHING_MARINE_LIFE = 'TOUCHING_MARINE_LIFE',
	TOUCHING_PLANTS = 'TOUCHING_PLANTS',
	TRANSPARENT_CLOTHING = 'TRANSPARENT_CLOTHING',
	TRIPODS = 'TRIPODS',
	UMBRELLAS = 'UMBRELLAS',
	UNACCOMPANIED_MINORS = 'UNACCOMPANIED_MINORS',
	UNDERWATER_CAMERAS = 'UNDERWATER_CAMERAS',
	VALUABLES = 'VALUABLES',
	VIDEO_RECORDING = 'VIDEO_RECORDING',
	VISIBLE_TATTOOS = 'VISIBLE_TATTOOS',
	WALKERS = 'WALKERS',
	WEAPONS_OR_SHARP_OBJECTS = 'WEAPONS_OR_SHARP_OBJECTS',
	WEARING_COSTUME = 'WEARING_COSTUME',
	WEARING_SHOES_INDOORS = 'WEARING_SHOES_INDOORS'
}

/** EU-regulated food allergens that may be present during the activity. */
export enum ActivityAllergen {
	CELERY = 'CELERY',
	CRUSTACEANS = 'CRUSTACEANS',
	EGGS = 'EGGS',
	FISH = 'FISH',
	GLUTEN = 'GLUTEN',
	LUPIN = 'LUPIN',
	MILK = 'MILK',
	MOLLUSCS = 'MOLLUSCS',
	MUSTARD = 'MUSTARD',
	NUTS = 'NUTS',
	PEANUTS = 'PEANUTS',
	SESAME = 'SESAME',
	SOY = 'SOY',
	SULPHITES = 'SULPHITES'
}

/** Mode of transport used during the activity. */
export enum ActivityTransportKind {
	BUS = 'BUS',
	CAR = 'CAR',
	TRAIN = 'TRAIN',
	PLANE = 'PLANE',
	BOAT = 'BOAT',
	BIKE = 'BIKE',
	OTHER = 'OTHER',
	NONE = 'NONE'
}

/** Whether the activity starts and ends at the same location. */
export enum ActivityTransportLocation {
	SAME_PLACE = 'SAME_PLACE',
	DIFFERENT_PLACE = 'DIFFERENT_PLACE'
}

/** Pet policy for the activity. */
export enum ActivityPetsAllowed {
	YES = 'YES',
	NO = 'NO',
	NOT_APPLY = 'NOT_APPLY'
}

/** Items included in the activity price. */
export enum ActivityIncluded {
	TICKETS_INCLUDED = 'TICKETS_INCLUDED',
	TICKETS_INCLUDED_BY_MODALITY = 'TICKETS_INCLUDED_BY_MODALITY',
	SKIP_THE_LINE = 'SKIP_THE_LINE',
	GUIDED_TOUR = 'GUIDED_TOUR',
	EXPERT_GUIDE = 'EXPERT_GUIDE',
	EXPERT_GUIDE_SPANISH = 'EXPERT_GUIDE_SPANISH',
	LOCAL_GUIDE_SPANISH = 'LOCAL_GUIDE_SPANISH',
	BUENDIA_TOUR_MANAGER = 'BUENDIA_TOUR_MANAGER',
	AUDIO_GUIDE_SPANISH = 'AUDIO_GUIDE_SPANISH',
	AUDIO_GUIDE_ENGLISH = 'AUDIO_GUIDE_ENGLISH',
	AUDIO_GUIDE_CHINESE = 'AUDIO_GUIDE_CHINESE',
	WIRELESS_RADIO_GUIDE = 'WIRELESS_RADIO_GUIDE',
	HEADPHONES = 'HEADPHONES',
	PRIVATE_BUS = 'PRIVATE_BUS',
	PRIVATE_BOAT = 'PRIVATE_BOAT',
	PRIVATE_TRAIN = 'PRIVATE_TRAIN',
	PRIVATE_VEHICLE = 'PRIVATE_VEHICLE',
	PUBLIC_TRANSPORT_TRAIN = 'PUBLIC_TRANSPORT_TRAIN',
	PUBLIC_TRANSPORT_BUS = 'PUBLIC_TRANSPORT_BUS',
	PUBLIC_TRANSPORT_FERRY = 'PUBLIC_TRANSPORT_FERRY',
	HOTEL_PICKUP = 'HOTEL_PICKUP'
}

/** Items not included in the activity price. */
export enum ActivityExcluded {
	TRANSPORT_TO_MEETING_POINT = 'TRANSPORT_TO_MEETING_POINT',
	TICKETS = 'TICKETS',
	TRANSPORT_TICKET = 'TRANSPORT_TICKET',
	GUIDED_TOUR = 'GUIDED_TOUR',
	INTERIOR_VISITS = 'INTERIOR_VISITS',
	FOOD_AND_DRINKS = 'FOOD_AND_DRINKS',
	TIPS = 'TIPS',
	HEADPHONES = 'HEADPHONES',
	SPORTS_EQUIPMENT = 'SPORTS_EQUIPMENT',
	OTHER = 'OTHER'
}

/** Type of multimedia asset attached to an activity. */
export enum MultimediaKind {
	IMAGE = 'IMAGE',
	VIDEO = 'VIDEO'
}

// ── Stages ──────────────────────────────────────

/** Nature of a stage within an activity itinerary. */
export enum StageKind {
	TRANSFER = 'TRANSFER',
	EXPERIENCE = 'EXPERIENCE'
}

/** Importance level of a stage. */
export enum StageRelevance {
	HIGH = 'HIGH',
	MEDIUM = 'MEDIUM',
	LOW = 'LOW',
	NONE = 'NONE'
}

/** Participation requirement for a stage. */
export enum StageRequirement {
	OPTIONAL = 'OPTIONAL',
	REQUIRED = 'REQUIRED',
	SUGGESTED = 'SUGGESTED',
	NONE = 'NONE'
}

// ── Sort ────────────────────────────────────────

/** Attributes available for sorting activity lists. */
export enum ActivitySortAttribute {
	CODE_REF = 'CODE_REF',
	TITLE = 'title'
}

// ── Meals ───────────────────────────────────────

/** Presentation format of a meal. */
export enum MealFormat {
	BARBECUE = 'BARBECUE',
	BUFFET = 'BUFFET',
	COMPLETE = 'COMPLETE',
	COURSE = 'COURSE',
	PICNIC = 'PICNIC',
	SNACK = 'SNACK',
	TAKE_AWAY = 'TAKE_AWAY',
	TASTING = 'TASTING'
}

/** Time-of-day classification for a meal. */
export enum MealKind {
	BREAKFAST = 'BREAKFAST',
	BRUNCH = 'BRUNCH',
	DEPEND_ON_HOUR = 'PENDING_HOUR',
	DINNER = 'DINNER',
	LUNCH = 'LUNCH',
	OTHER = 'OTHER'
}

/** Dietary and sourcing labels applicable to a meal. */
export enum MealAdditional {
	VEGETARIAN = 'VEGETARIAN',
	VEGAN = 'VEGAN',
	GLUTEN_FREE = 'GLUTEN_FREE',
	LACTOSE_FREE = 'LACTOSE_FREE',
	NUT_FREE = 'NUT_FREE',
	SOY_FREE = 'SOY_FREE',
	MUSHROOM_FREE = 'MUSHROOM_FREE',
	SEAFOOD_FREE = 'SEAFOOD_FREE',
	SHELLFISH_FREE = 'SHELLFISH_FREE',
	EGG_FREE = 'EGG_FREE',
	PALEO = 'PALEO',
	KETO = 'KETO',
	MEDITERRANEAN = 'MEDITERRANEAN',
	FRESH = 'FRESH',
	LOCAL = 'LOCAL',
	ORGANIC = 'ORGANIC',
	BIO = 'BIO'
}
